import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiOutlineWhatsApp, AiOutlineGithub } from 'react-icons/ai'
import Image from 'next/image'
import frontDami from '../public/frontDami.png';
import consulting from '../public/consulting.png'
import design from '../public/design.png'
import code from '../public/code.png'
import { DiJavascript1, DiReact } from 'react-icons/di'
import { SiRedux } from 'react-icons/si'
import { SiTypescript } from 'react-icons/si'
import ecomm1 from '../public/ecomm1.gif'
import pelisapp from '../public/pelisApp.png'
import currconverter from '../public/Currencyconv.png'
// import resume from '../public/damianjsanchezresume.pdf'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>DJS myPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-200 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-slate-300 animate-pulse'>Hi, It`s developed by DJS</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='text-yellow-600 cursor-pointer text-3xl dark:text-slate-300' onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <a className='bg-gradient-to-r from-green-500 to-blue-500 text-white px-4 py-3 rounded-xl ml-8' href="/damianjsanchezresume.pdf" download target="_blank" rel="noreferrer">
                  My Resume
                  <span className="relative inline-flex rounded-full h-4 w-4 bg-green-400 animate-ping ml-4 p-2"></span>
                </a>

              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-green-600 font-medium md:text-6xl'>Damian Javier Sanchez</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-slate-400'>Front-End Web developer</h3>
            <p className='text-lg py-5 leading-8 text-gray-800 shadow-slate-300 md:text-2xl max-w-lg mx-auto dark:text-slate-200'>
              I am resilient keen to programming webs with passion putting my knowledge on the details.
              Join me down below!.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-slate-200'>
            <a href='https://www.linkedin.com/in/damianjaviersanchez/' target="_blank" rel='noreferrer'>
              <AiFillLinkedin />
            </a>
            <a href='https://github.com/sanchezdamianj' target="_blank" rel='noreferrer'>
              <AiOutlineGithub />
            </a>
            <a href='https://wa.me/5491157098362' target="_blank" rel='noreferrer'>
              <AiOutlineWhatsApp />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-green-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={frontDami} alt='Dami Frontend' priority blurDataURL='' layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-slate-200'>Services i can offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-300'>
              Since the beggining of my journey as Frontend engineer, i’ve done Remote Work with
              <span className='text-blue-500'> larger team</span> and by my own.
              I would like to work with <span className='text-blue-500'>startups</span> or be part of a <span className='text-blue-500'>company</span>

            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-300'>
              I offer from a wide range of services, including frontend, consulting, programming and an open minded to learn by doing.
            </p>
          </div>
          <div className='md:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100} alt='from design to code' />
              <h3 className='text-lg font-medium pt-8 pb-2'>From Design to Code</h3>
              <p>
                Creating Code to render a clean UIs suits for your needs following good practices, and taking into account the details based on th user experience
              </p>
              <h4 className='py-4 text-blue-600'>Design tools what i can handle</h4>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100} alt='Programming' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Technologies</h3>
              <p>

                Despite that I don’t have a favorite language to work with, I’m keen to JavaScript, ReactJS and TypeScript. However, I’m looking forward to new oportunities to learn exciting technologies.
              </p>
              <h4 className='py-4 text-blue-600'>Languages, libraries & frameworks  what i can handle</h4>
              <p className='text-gray-800 py-1'>JavaScript, React, Redux toolkit, TypeScript</p>
              <div className='flex justify-center items-center gap-8 py-1'>
                <DiJavascript1 size={30} className='bg-yellow-400' />
                <DiReact size={35} className='text-cyan-500' />
                <SiRedux size={30} className='text-violet-400' />
                <SiTypescript size={30} className='bg-white-100 text-blue-400' />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} alt='Consultant Resource' />
              <h3 className='text-lg font-medium pt-8 pb-2'>From Client to a Project</h3>
              <p>
                As System Engineer, and a long experience in consulting, i can work with the client to figure out which is the better client needs.
              </p>
              <h4 className='py-4 text-blue-600'>Senior Consultant as background</h4>
              <p className='text-gray-800 py-1'>System engineer</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-slate-200'>Services i can offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-300'>
              Since the beggining of my journey as Frontend engineer, i’ve done Remote Work with
              <span className='text-blue-500 dark:text-blue-200'> larger team</span> and by my own.
              I would like to work with <span className='text-blue-500 dark:text-blue-200'>startups</span> or be part of a <span className='text-blue-500'>company</span>

            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-slate-300'>
              I offer from a wide range of services, including frontend, consulting, programming and an open minded to learn by doing.
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3'>
              <Image src={ecomm1} className='rounded-lg' width={'100%'} height={'100%'} layout="responsive" alt='E-commerce' />
              <span className='text-blue-500 text-lg font-medium'>Link to: https://ecommerce-five-chi.vercel.app/login</span>
            </div>
            <div className='basis-1/3'>
              <Image src={pelisapp} className='rounded-lg' width={'100%'} height={'100%'} layout="responsive" alt='App for Tv shows and movies consuming API' />
            </div >
            <div className='basis-1/3'>
              <Image src={currconverter} className='rounded-lg' width={'100%'} height={'100%'} layout="responsive" alt='Currency converter' />
            </div>
          </div>
        </section>

      </main>

      <footer className=" bg-gray-900 dark:bg-slate-600">
        <div className="max-w-2xl mx-auto text-white py-10">
          <div className="text-center">
            <h3 className="text-3xl mb-3"> Portfolio app using Nextjs, React JS, Tailwind css </h3>
            <p> Stay focus. All day, every day & you will reach your goals. </p>
            <div className="flex justify-center my-10">
              <div className="flex items-center border rounded-lg px-4 py-2 w-52 mx-2">
                {/* <Image src="https://cdn-icons-png.flaticon.com/512/888/888857.png" layout='fill' class="w-7 md:w-8" alt='f1' /> */}
                <div className="text-left ml-3">
                  <p className='text-md text-gray-200 text-semibold'>Improving skills like: </p>
                  <p className="text-sm md:text-base font-medium"> TypeScript && Redux toolkit/ RKT Query </p>
                </div>
              </div>
              <div className="flex items-center border rounded-lg px-4 py-2 w-44 mx-2">
                {/* <Image src="https://cdn-icons-png.flaticon.com/512/888/888841.png" layout='fill' class="w-7 md:w-8"  alt='f2'/> */}
                <div className="text-left ml-3">
                  <p className='text-md text-gray-200 text-semibold'> Learning skills to be FullStack MERN: </p>
                  <p className="text-md md:text-base font-medium"> Backend skills like Node JS, Express, MongoDB</p>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-28 flex flex-col md:flex-row md:justify-between items-center text-sm text-gray-400">
            <p className="order-2 md:order-1 mt-8 md:mt-0"> &copy; Damian J. Sanchez, 2022. </p>
            <div className="order-1 md:order-2">
              <span className="px-2 border-l">Contact me +54 9 11-5709-8362</span>
              <span className="px-2 border-l">Privacy Policy</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

